#!/usr/bin/env bash
set -euo pipefail

CONFIG="/etc/cert-monitor/config.yaml"
NGINX_CONF_D="/etc/nginx/conf.d"

log() { echo -e "\e[1;32m[cert-monitor]\e[0m $*"; }

# Проверим, что конфиг смонтирован.
if [[ ! -f "$CONFIG" ]]; then
    echo "[cert-monitor] ОШИБКА: не найден $CONFIG (смонтируйте файл в контейнер)" >&2
    exit 1
fi

# Генерируем server-блоки для каждого домена (webroot на 80, HTTPS на 443),
# если они не созданы ранее. Используем небольшой Python-скрипт из приложения.
log "Генерация nginx-конфигурации для доменов..."
python3 - <<'PY'
import re
import yaml
from pathlib import Path

cfg_path = Path("/etc/cert-monitor/config.yaml")
conf_d = Path("/etc/nginx/conf.d")

with cfg_path.open("r", encoding="utf-8") as fh:
    raw = yaml.safe_load(fh) or {}

domains = raw.get("domains", [])
names = []
for d in domains:
    if isinstance(d, str):
        names.append(d)
    elif isinstance(d, dict) and d.get("name"):
        names.append(d["name"])

if not names:
    raise SystemExit("в конфиге нет доменов")

blocks = []
for name in names:
    blocks.append(f"""
server {{
    listen 80;
    listen [::]:80;
    server_name {name};

    location /.well-known/acme-challenge/ {{
        root /var/www/certbot;
        default_type "text/plain";
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name {name};

    ssl_certificate     /etc/letsencrypt/live/{name}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{name}/privkey.pem;

    location /.well-known/acme-challenge/ {{
        root /var/www/certbot;
        default_type "text/plain";
    }}

    location / {{
        return 200 'ok\\n';
        add_header Content-Type text/plain;
    }}
}}
"""
    )

target = conf_d / "cert-monitor-domains.conf"
if not target.exists():
    target.write_text("# Auto-generated by cert_monitor entrypoint.\n" + "\n".join(blocks), encoding="utf-8")
    log(f"Создан {target} для {len(names)} домена(ов)")
else:
    log(f"{target} уже существует, не перезаписываю")
PY

# Стартуем nginx.
log "Запуск nginx..."
nginx -t
nginx

# Передаём управление приложению (планировщик / явный режим).
log "Запуск cert_monitor..."
exec python3 -m cert_monitor --config "$CONFIG" "$@"