# Держим certbot вебрут доступным и без сертификата (на случай первого выпуска).
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    # Редирект остального трафика на HTTPS.
    location / {
        return 301 https://$host$request_uri;
    }
}